FROM python:3
COPY myapp.py /
COPY templates/index.html templates/index.html
COPY stonkGraph.py stonkGraph.py
RUN pip install flask
RUN pip install numpy
RUN pip install pandas
RUN pip install matplotlib
RUN pip install plotly
RUN pip install yfinance
RUN pip install pandas_datareader
RUN pip install dash==1.16.2
CMD [ "python", "./myapp.py" ]
